apiVersion: v1
kind: Service
metadata:
  name: grpc-server
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerIP: "10.3.0.6"
  externalTrafficPolicy: Cluster
  ports:
  - name: grpc
    port: 443
    targetPort: grpc
    appProtocol: HTTP2
  selector: 
    app: grpc-server